# Generated by Django 6.0.3 on 2026-07-13 16:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='global_state', max_length=50, unique=True)),
                ('phong_thi_goc', models.TextField(default='[]')),
                ('tui_phach', models.TextField(default='[]')),
                ('phieu_giao_nhan', models.TextField(default='[]')),
                ('can_bo_coi_thi', models.TextField(default='[]')),
                ('phuc_khao', models.TextField(default='[]')),
                ('audit_logs', models.TextField(default='[]')),
                ('system_configs', models.TextField(default='{}')),
                ('ky_thi', models.TextField(default='[]')),
                ('ca_thi', models.TextField(default='[]')),
                ('lich_thi', models.TextField(default='[]')),
                ('hoc_phi', models.TextField(default='[]')),
                ('lop_thi_diem', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='BaiThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phach', models.CharField(max_length=50, unique=True)),
                ('ma_sinh_vien', models.CharField(blank=True, max_length=50, null=True)),
                ('ho_ten_sinh_vien', models.CharField(blank=True, max_length=255, null=True)),
                ('diem_lan_1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('diem_lan_2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('diem_phuc_khao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('diem_cuoi_cung', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HocPhan',
            fields=[
                ('ma_hoc_phan', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('ten_hoc_phan', models.CharField(max_length=255, verbose_name='Tên Học phần')),
            ],
        ),
        migrations.CreateModel(
            name='KyThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ky_thi', models.CharField(max_length=255, verbose_name='Tên Kỳ thi')),
                ('nam_hoc', models.CharField(max_length=20, verbose_name='Năm học')),
                ('hoc_ky', models.CharField(max_length=20, verbose_name='Học kỳ')),
                ('ngay_bat_dau', models.DateField(verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.DateField(verbose_name='Ngày kết thúc')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('tkt', 'Tổ Khảo thí'), ('tkct', 'Thư ký Chấm thi'), ('dvcm', 'Đơn vị Chuyên môn'), ('gv', 'Giảng viên'), ('ldp', 'Lãnh đạo phòng'), ('cvht', 'Cố vấn học tập / Admin')], max_length=10, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và Tên')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DonPhucKhao',
            fields=[
                ('ma_don', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ly_do', models.TextField()),
                ('trang_thai', models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('dang_xu_ly', 'Đang xử lý'), ('da_co_ket_qua', 'Đã có kết quả'), ('da_phe_duyet', 'Đã phê duyệt')], default='cho_xu_ly', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('bai_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khaothi_app.baithi')),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CauHinhPhucKhao',
            fields=[
                ('ma_cau_hinh', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('thoi_gian_mo_cong', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_khoa_cong', models.DateTimeField(blank=True, null=True)),
                ('han_chot_cham', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(default='KichHoat', max_length=50)),
                ('ma_hoc_phan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khaothi_app.hocphan')),
            ],
        ),
        migrations.CreateModel(
            name='CaThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ca_thi', models.CharField(max_length=100, verbose_name='Tên Ca thi')),
                ('ngay_thi', models.DateField(verbose_name='Ngày thi')),
                ('gio_bat_dau', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('gio_ket_thuc', models.TimeField(verbose_name='Giờ kết thúc')),
                ('ky_thi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ca_thi', to='khaothi_app.kythi', verbose_name='Kỳ thi')),
            ],
        ),
        migrations.CreateModel(
            name='PhienBanCotDiem',
            fields=[
                ('ma_phien_ban', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ten_phien_ban', models.CharField(max_length=255)),
                ('thoi_gian_ap_dung', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_cong_bo', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(default='ApDung', max_length=50)),
                ('ma_hoc_phan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khaothi_app.hocphan')),
            ],
        ),
        migrations.CreateModel(
            name='PhongThiGoc',
            fields=[
                ('ma_phong', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('so_luong_bai_thi', models.PositiveIntegerField(default=0)),
                ('trang_thai', models.CharField(default='Chưa xử lý', max_length=50)),
                ('ca_thi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khaothi_app.cathi')),
                ('hoc_phan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khaothi_app.hocphan')),
            ],
        ),
        migrations.CreateModel(
            name='TuiPhach',
            fields=[
                ('ma_tui_phach', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('so_luong_bai_thi', models.PositiveIntegerField(default=0)),
                ('trang_thai', models.CharField(choices=[('moi_tao', 'Mới tạo'), ('da_doi_chieu', 'Đã đối chiếu'), ('da_khoa_phach', 'Đã khóa phách'), ('da_phan_cong', 'Đã phân công chấm'), ('dang_cham', 'Đang chấm'), ('da_cham_xong', 'Đã chấm xong'), ('da_len_diem', 'Đã lên điểm'), ('da_duyet', 'Đã duyệt')], default='moi_tao', max_length=20)),
                ('mat_khau', models.CharField(blank=True, max_length=128, null=True, verbose_name='Mật khẩu túi phách')),
                ('giang_vien_cham_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tui_phach_cham_1', to=settings.AUTH_USER_MODEL)),
                ('giang_vien_cham_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tui_phach_cham_2', to=settings.AUTH_USER_MODEL)),
                ('hoc_phan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khaothi_app.hocphan')),
                ('phong_thi_goc', models.ManyToManyField(related_name='tui_phach', to='khaothi_app.phongthigoc')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuGiaoNhan',
            fields=[
                ('ma_phieu', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('thoi_gian_giao', models.DateTimeField(auto_now_add=True)),
                ('thoi_gian_nhan', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('da_hoan_tat', 'Đã hoàn tất'), ('da_huy', 'Đã hủy')], default='cho_xac_nhan', max_length=20)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nguoi_giao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phieu_da_giao', to=settings.AUTH_USER_MODEL)),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phieu_da_nhan', to=settings.AUTH_USER_MODEL)),
                ('phong_thi_dinh_kem', models.ManyToManyField(blank=True, to='khaothi_app.phongthigoc')),
                ('tui_phach_dinh_kem', models.ManyToManyField(blank=True, to='khaothi_app.tuiphach')),
            ],
        ),
        migrations.AddField(
            model_name='baithi',
            name='tui_phach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_thi', to='khaothi_app.tuiphach'),
        ),
    ]
