# Generated by Django 6.0.3 on 2026-07-14 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khaothi_app', '0002_maphach_lophanhchinh_phongthi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nhan_vien', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=255)),
                ('don_vi', models.CharField(blank=True, max_length=255, null=True)),
                ('sdt', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhan_vien_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
