# Generated by Django 6.0.3 on 2026-07-14 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khaothi_app', '0003_nhanvien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('ma_khoa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ten_khoa', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='giangvien',
            name='don_vi',
        ),
        migrations.AddField(
            model_name='giangvien',
            name='khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='giang_vien', to='khaothi_app.khoa'),
        ),
        migrations.AddField(
            model_name='hocphan',
            name='khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hoc_phan', to='khaothi_app.khoa'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nhan_vien', to='khaothi_app.khoa'),
        ),
    ]
