# Generated by Django 6.0.3 on 2026-07-14 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khaothi_app', '0004_khoa_remove_giangvien_don_vi_giangvien_khoa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maphach',
            name='sbd',
        ),
        migrations.RemoveField(
            model_name='maphach',
            name='sinh_vien',
        ),
        migrations.RemoveField(
            model_name='tuiphach',
            name='lich_thi',
        ),
        migrations.AddField(
            model_name='maphach',
            name='thi_sinh',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_phach', to='khaothi_app.danhsachthisinh'),
        ),
        migrations.CreateModel(
            name='TuiBaiThi',
            fields=[
                ('ma_tui_bai', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('so_luong_bai', models.PositiveIntegerField(default=0)),
                ('trang_thai', models.CharField(default='DaThuHoi', max_length=50)),
                ('lich_thi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tui_bai_thi', to='khaothi_app.lichthi')),
            ],
        ),
        migrations.AddField(
            model_name='tuiphach',
            name='tui_bai_thi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tui_phach', to='khaothi_app.tuibaithi'),
        ),
    ]
