# Generated by Django 6.0.4 on 2026-07-24 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khaothi_app', '0010_remove_user_sub_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhatkyinsao',
            name='ghi_chu_kiem_tra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhatkyinsao',
            name='ket_qua_kiem_tra',
            field=models.CharField(blank=True, choices=[('Khop', 'Khớp'), ('KhongKhop', 'Không khớp')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nhatkyinsao',
            name='nguoi_kiem_tra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nhat_ky_in_sao_da_kiem_tra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nhatkyinsao',
            name='thoi_gian_kiem_tra',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dotinsao',
            name='trang_thai',
            field=models.CharField(choices=[('ChoCapNhat', 'Chờ cập nhật nhật ký'), ('DaCapNhat', 'Đã cập nhật nhật ký (Chờ xác nhận)'), ('HoanTat', 'Hoàn tất'), ('CanXuLyLai', 'Cần xử lý lại'), ('TuChoi', 'Từ chối xác nhận')], default='ChoCapNhat', max_length=50),
        ),
        migrations.AlterField(
            model_name='phongthi',
            name='trang_thai',
            field=models.CharField(default='Khả dụng', max_length=50),
        ),
        migrations.CreateModel(
            name='ChecklistInSao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_muc', models.CharField(max_length=50)),
                ('ten_muc', models.CharField(max_length=255, verbose_name='Tên học phần / Mục checklist')),
                ('nhom_de', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nhóm đề')),
                ('so_luong_can_in', models.PositiveIntegerField(default=0)),
                ('so_luong_da_in', models.PositiveIntegerField(default=0)),
                ('so_luong_niem_phong', models.PositiveIntegerField(default=0)),
                ('thoi_gian_thuc_hien', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('ChuaIn', 'Chưa in'), ('DaInXong', 'Đã in xong')], default='ChuaIn', max_length=50)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('dot_in_sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_checklist', to='khaothi_app.dotinsao')),
            ],
        ),
    ]
