# Generated by Django 6.0.4 on 2026-07-24 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khaothi_app', '0011_nhatkyinsao_ghi_chu_kiem_tra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinsao',
            name='hoc_phan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_in_sao', to='khaothi_app.hocphan'),
        ),
    ]
