# Generated by Django 6.0.4 on 2026-07-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khaothi_app', '0012_checklistinsao_hoc_phan'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinsao',
            name='da_dat',
            field=models.BooleanField(default=False, verbose_name='Đạt tiêu chí chất lượng'),
        ),
        migrations.AddField(
            model_name='checklistinsao',
            name='loai_muc',
            field=models.CharField(choices=[('NhomDe', 'Nhóm đề / Học phần'), ('TieuChi', 'Tiêu chí chất lượng')], default='NhomDe', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklistinsao',
            name='ten_muc',
            field=models.CharField(max_length=255, verbose_name='Tên học phần / Tiêu chí checklist'),
        ),
    ]
