# Generated by Django 6.0.4 on 2026-07-26 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khaothi_app', '0013_checklistinsao_da_dat_checklistinsao_loai_muc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieugiaonhan',
            name='bien_ban_giao_nhan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CauHinhHeThong',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('nguoi_cap_nhat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cau_hinh_he_thong_cap_nhat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CauHinhThoiGianDotThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_hoc', models.CharField(max_length=20)),
                ('hoc_ky', models.CharField(max_length=20)),
                ('dot_thi', models.CharField(max_length=50)),
                ('tg_bat_dau_nhap', models.DateTimeField(blank=True, null=True)),
                ('tg_khoa_cong_nhap', models.DateTimeField(blank=True, null=True)),
                ('tg_cong_bo_diem', models.DateTimeField(blank=True, null=True)),
                ('tg_nop_de_thi', models.DateTimeField(blank=True, null=True)),
                ('tg_nhap_diem_tp', models.DateTimeField(blank=True, null=True)),
                ('tg_cau_hinh_trong_so', models.DateTimeField(blank=True, null=True)),
                ('tg_chot_dieu_kien_thi', models.DateTimeField(blank=True, null=True)),
                ('tg_chot_quy_doi', models.DateTimeField(blank=True, null=True)),
                ('tg_mo_nhan_don_pk', models.DateTimeField(blank=True, null=True)),
                ('tg_khoa_nhan_don_pk', models.DateTimeField(blank=True, null=True)),
                ('han_chot_cham_pk', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('nam_hoc', 'hoc_ky', 'dot_thi')},
            },
        ),
        migrations.CreateModel(
            name='QuyetToanThuLao',
            fields=[
                ('ma_quyet_toan', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngay_duyet', models.DateTimeField(blank=True, null=True)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('trang_thai', models.CharField(default='ChoDuyet', max_length=50)),
                ('ky_thi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quyet_toan_thu_lao', to='khaothi_app.kythi')),
                ('nguoi_duyet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quyet_toan_thu_lao_duyet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
