# Generated by Django 6.0.4 on 2026-07-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khaothi_app', '0014_phieugiaonhan_bien_ban_giao_nhan_cauhinhhethong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstate',
            name='danh_sach_thi_data',
            field=models.TextField(default='[]'),
        ),
    ]
