# Generated by Django 6.0.3 on 2026-07-29 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khaothi_app', '0015_add_danh_sach_thi_data_to_appstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donphuckhao',
            name='hoc_phan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don_phuc_khao', to='khaothi_app.hocphan'),
        ),
        migrations.AddField(
            model_name='donphuckhao',
            name='ngay_duyet',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donphuckhao',
            name='nguoi_duyet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_phuc_khao_duyet', to=settings.AUTH_USER_MODEL),
        ),
    ]
