# Generated by Django 6.0.3 on 2026-07-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khaothi_app', '0016_donphuckhao_hoc_phan_donphuckhao_ngay_duyet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donphuckhao',
            name='ngay_duyet',
        ),
        migrations.RemoveField(
            model_name='donphuckhao',
            name='nguoi_duyet',
        ),
    ]
